<html>
    <head>
        <meta charset="UTF-8">
        <link rel="stylesheet" type="text/css" href="style.css">

    </head>
    <body>
    <div>
        <button><a href="home.php">Home</a></button>
        <button><a href="inclui.php">Incluir</a></button>
        <button><a href="exclui.php">Excluir</a></button>
        <button><a href="mostra.php">Mostrar</a></button>
        <br>
    </div>
    </body>
</html>




